#!/usr/bin/env python3
"""Generate Android map marker icons (expo-maps GoogleMaps markers can't draw a
monogram/tint like AppleMaps, so we ship PNG icons):

  - cat-<category>.png  teardrop pin in the category colour (single shelter)
  - cluster-<n>.png     filled circle + white count (n = 2..99)
  - cluster-99plus.png  the "99+" bucket

Also emits lib/markerIconSources.ts — a { key: require(...) } map the app loads
via expo-image. Run: python3 scripts/gen-marker-icons.py  (needs Pillow).
"""
from __future__ import annotations

import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "markers")
TS = os.path.join(ROOT, "lib", "markerIconSources.ts")

CLUSTER_COLOR = "#1B4D8C"
CATEGORY_COLOR = {
    "kas": "#0F766E",
    "priedanga": "#1B4D8C",
    "evakuacija": "#B45309",
    "sirena": "#7C2D12",
}
WHITE = (255, 255, 255, 255)
S = 3  # supersample factor for crisp edges


def font(size: int) -> ImageFont.FreeTypeFont:
    for p in (
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/Library/Fonts/Arial.ttf",
    ):
        if os.path.exists(p):
            return ImageFont.truetype(p, size)
    return ImageFont.load_default()


def teardrop(color: str, path: str) -> None:
    w, h = 60 * S, 78 * S
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    r = 26 * S
    cx, cy = w // 2, r + 3 * S
    border = 4 * S
    # tail: triangle from circle bottom to the tip
    d.polygon([(cx - r + 6 * S, cy + 8 * S), (cx + r - 6 * S, cy + 8 * S), (cx, h - 3 * S)], fill=WHITE)
    d.ellipse([cx - r - border, cy - r - border, cx + r + border, cy + r + border], fill=WHITE)
    d.polygon([(cx - r + 9 * S, cy + 7 * S), (cx + r - 9 * S, cy + 7 * S), (cx, h - 7 * S)], fill=color)
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=color)
    d.ellipse([cx - 8 * S, cy - 8 * S, cx + 8 * S, cy + 8 * S], fill=WHITE)  # inner dot
    img.resize((w // S, h // S), Image.LANCZOS).save(path)


def cluster(label: str, path: str) -> None:
    d3 = 84 * S
    img = Image.new("RGBA", (d3, d3), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    border = 5 * S
    d.ellipse([border, border, d3 - border, d3 - border], fill=WHITE)
    pad = border + 4 * S
    d.ellipse([pad, pad, d3 - pad, d3 - pad], fill=CLUSTER_COLOR)
    fsize = 40 * S if len(label) <= 2 else 30 * S
    f = font(fsize)
    box = d.textbbox((0, 0), label, font=f)
    tw, th = box[2] - box[0], box[3] - box[1]
    d.text(((d3 - tw) / 2 - box[0], (d3 - th) / 2 - box[1]), label, font=f, fill=WHITE)
    img.resize((d3 // S, d3 // S), Image.LANCZOS).save(path)


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    entries: list[tuple[str, str]] = []

    for code, color in CATEGORY_COLOR.items():
        name = f"cat-{code}.png"
        teardrop(color, os.path.join(OUT, name))
        entries.append((f"cat_{code}", name))

    for n in range(2, 100):
        name = f"cluster-{n}.png"
        cluster(str(n), os.path.join(OUT, name))
        entries.append((f"c{n}", name))
    cluster("99+", os.path.join(OUT, "cluster-99plus.png"))
    entries.append(("c99plus", "cluster-99plus.png"))

    lines = [
        "// AUTO-GENERATED by scripts/gen-marker-icons.py — do not edit by hand.",
        "// Android map marker icons (expo-maps can't draw monogram/tint like iOS).",
        "/* eslint-disable */",
        "export const MARKER_ICON_SOURCES: Record<string, number> = {",
    ]
    for key, name in entries:
        lines.append(f"  '{key}': require('../assets/markers/{name}'),")
    lines.append("};")
    with open(TS, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated {len(entries)} icons in {OUT} and {TS}")


if __name__ == "__main__":
    main()
